<a href="https://colab.research.google.com/github/codeguy186/ML-and-DL/blob/main/TF1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MAKING TENSORS|
MANIPULATING TENSORS|
GETTING INFO FROM TENSORS.


In [ ]:
#Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [ ]:
#Create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check number of dimensions
scalar.ndim

0

In [ ]:
#create a vector
vector=tf.constant([1,1])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create a matrix
matrix=tf.constant([[1,1],[2,2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 2]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix2=tf.constant([[1.,2.],[3.,4.]],dtype=tf.float16)
matrix2

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [ ]:
#create a tensor
tensor=tf.constant([[[1,1,1],
                     [2,2,2],
                     [3,3,3]],[[3,2,1],[4,3,1],[4,8,9]]])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[3, 2, 1],
        [4, 3, 1],
        [4, 8, 9]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
#Creating tensors with Variable
tensor2=tf.Variable([1,1])
tensor2

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 1], dtype=int32)>

In [ ]:
#change variable in mutable tensor made using Variable()
tensor2[0].assign(8)
tensor2

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 1], dtype=int32)>

In [ ]:
#create random tensor
r1=tf.random.Generator.from_seed(40)
r1=r1.normal(shape=(2,2))
r2=tf.random.Generator.from_seed(9)
r2=r2.normal(shape=(2,2))
r3=tf.random.Generator.from_seed(40)
r3=r3.normal(shape=(3,2))
r1==r3# same seed and shape produces same tensor
r3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.78953624,  0.53897345],
       [-0.48535708,  0.74055266],
       [ 0.31662667, -1.4391748 ]], dtype=float32)>

In [ ]:
#shuffle the order of elements in a tensor
tf.random.shuffle(r3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.48535708,  0.74055266],
       [ 0.78953624,  0.53897345],
       [ 0.31662667, -1.4391748 ]], dtype=float32)>

In [ ]:
r3
tf.random.shuffle(r3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.31662667, -1.4391748 ],
       [ 0.78953624,  0.53897345],
       [-0.48535708,  0.74055266]], dtype=float32)>

In [ ]:
tf.random.set_seed(40)#global level random seed fixes the order
tf.random.shuffle(r3)#operation level random seed

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.48535708,  0.74055266],
       [ 0.78953624,  0.53897345],
       [ 0.31662667, -1.4391748 ]], dtype=float32)>

In [ ]:

tf.ones([10,7])
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
#using numpy
import numpy as np
A=np.arange(1,50)
A
tf.constant(A,shape=(7,1,7))

<tf.Tensor: shape=(7, 1, 7), dtype=int64, numpy=
array([[[ 1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19, 20, 21]],

       [[22, 23, 24, 25, 26, 27, 28]],

       [[29, 30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41, 42]],

       [[43, 44, 45, 46, 47, 48, 49]]])>

In [ ]:
#getting info from tensors
r4t=tf.zeros([1,2,3,4])
r4t


<tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
r4t[0]

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
r4t[:,1]

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
r4t[:,:,1]

<tf.Tensor: shape=(1, 2, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
r4t[:,:,:,0]
tf.size(r4t).numpy()

24

In [ ]:
#indexing tensors
r4t[:2,:2,:2,:2]#getting first 2 elements from each dimension

<tf.Tensor: shape=(1, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#get the first element of every index except the last dimension
r4t[:1,:1,:1].numpy()

array([[[[0., 0., 0., 0.]]]], dtype=float32)

In [ ]:
#expanding a tensor
r2t=tf.constant([[10,7],[5,6]])
r2t.ndim

2

In [ ]:
#get last item from each row
r2t[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 6], dtype=int32)>

In [ ]:
#expanding a tensor
r3t=r2t[...,tf.newaxis]
r3t

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 5],
        [ 6]]], dtype=int32)>

In [ ]:
tf.expand_dims(r2t,axis=-1)#expand last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 5],
        [ 6]]], dtype=int32)>

In [ ]:
#manipulating tensors
r2t+20
tf.add(r2t,20)#faster

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 27],
       [25, 26]], dtype=int32)>

In [ ]:
r2t*7
tf.multiply(r2t,7)#faster

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[70, 49],
       [35, 42]], dtype=int32)>

In [ ]:
#matrix multiplication
a=tf.constant([[1,1,1],[2,1,3],[5,1,7]])
b=tf.constant([[1,2],[2,0],[0,1]])
print("a*b is\n",tf.matmul(a,b).numpy())
print("a*b is\n",a@b)


a*b is
 [[ 3  3]
 [ 4  7]
 [ 7 17]]
a*b is
 tf.Tensor(
[[ 3  3]
 [ 4  7]
 [ 7 17]], shape=(3, 2), dtype=int32)


In [ ]:
x=tf.constant([[1,2,3],[3,4,5],[6,7,8]])
y=tf.constant([[1,2,3],[3,4,5]])
yr=tf.reshape(y,(3,2))
yt=tf.transpose(y)
print("y reshaped",yr.numpy())
print("y transpose",yt.numpy())

print("using reshape",tf.matmul(x,yr).numpy())
print("using transpose",tf.matmul(x,yt).numpy())



y reshaped [[1 2]
 [3 3]
 [4 5]]
y transpose [[1 3]
 [2 4]
 [3 5]]
using reshape [[19 23]
 [35 43]
 [59 73]]
using transpose [[14 26]
 [26 50]
 [44 86]]


In [ ]:
#changing datatype of a tensor
d=tf.constant([[1.2,3.4],[2,6]])
print("initially",d.dtype)
d=tf.cast(d,tf.float16)
print("after changing",d.dtype)#float16 can run faster

initially <dtype: 'float32'>
after changing <dtype: 'float16'>


In [ ]:
#Aggregating tensors
e=tf.constant([-10,5])
tf.abs(e) #absolute value


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  5], dtype=int32)>

In [ ]:
s=tf.random.Generator.from_seed(10)
s=s.normal(shape=(3,3))
s

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.29604465, -0.21134205,  0.01063002],
       [ 1.5165398 ,  0.27305737, -0.29925638],
       [-0.3652325 ,  0.61883307, -1.0130816 ]], dtype=float32)>

In [ ]:
#find min value
min=tf.math.reduce_min(s)
min.numpy()#minimum of whole matrix
mincol=tf.math.reduce_min(s,axis=0)#minimum in each column
mincol.numpy()

array([-0.3652325 , -0.21134205, -1.0130816 ], dtype=float32)

In [ ]:
#find max value
max=tf.math.reduce_max(s)
max.numpy()#max of whole matrix
maxrow=tf.math.reduce_max(s,axis=1)#max in each row
maxrow.numpy()

array([0.01063002, 1.5165398 , 0.61883307], dtype=float32)

In [ ]:
#find mean of tensor
mean=tf.math.reduce_mean(s)
print(mean.numpy())#mean of whole matrix
meancol=tf.math.reduce_mean(s,axis=0)#mean of each col
meancol.numpy()

0.026011467


array([ 0.2850876 ,  0.22684945, -0.43390265], dtype=float32)

In [ ]:
#find sum of tensor
sum=tf.math.reduce_sum(s)
print(sum.numpy())#sum of whole matrix
sumrow=tf.math.reduce_sum(s,axis=1)#sum of each row
sumrow.numpy()

0.2341032


array([-0.49675667,  1.4903407 , -0.75948095], dtype=float32)

In [ ]:
#finding position of max value
maxi=tf.argmax(s,axis=1)# max value indices of each row



In [ ]:
#squeezing a tensor
m=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
m

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.74675906, 0.24612856, 0.52820086, 0.8276756 , 0.6183318 ,
           0.0846777 , 0.13903832, 0.04563856, 0.6154578 , 0.44305432,
           0.7431537 , 0.9795221 , 0.54386437, 0.21016955, 0.24788725,
           0.35024524, 0.03533351, 0.65845823, 0.24004912, 0.1725409 ,
           0.22278512, 0.2606182 , 0.37575412, 0.9490981 , 0.3538996 ,
           0.4968046 , 0.18215156, 0.87830687, 0.08035612, 0.9584689 ,
           0.11927223, 0.48161948, 0.46814215, 0.26376808, 0.33337045,
           0.9157454 , 0.8242643 , 0.00191033, 0.2706449 , 0.75256467,
           0.07479346, 0.25697482, 0.10337758, 0.5379051 , 0.2707088 ,
           0.02460349, 0.06105328, 0.42337906, 0.30669105, 0.30637336]]]]],
      dtype=float32)>

In [ ]:
msq=tf.squeeze(m)#removes dimensions with value 1 from tensor
msq,msq.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.74675906, 0.24612856, 0.52820086, 0.8276756 , 0.6183318 ,
        0.0846777 , 0.13903832, 0.04563856, 0.6154578 , 0.44305432,
        0.7431537 , 0.9795221 , 0.54386437, 0.21016955, 0.24788725,
        0.35024524, 0.03533351, 0.65845823, 0.24004912, 0.1725409 ,
        0.22278512, 0.2606182 , 0.37575412, 0.9490981 , 0.3538996 ,
        0.4968046 , 0.18215156, 0.87830687, 0.08035612, 0.9584689 ,
        0.11927223, 0.48161948, 0.46814215, 0.26376808, 0.33337045,
        0.9157454 , 0.8242643 , 0.00191033, 0.2706449 , 0.75256467,
        0.07479346, 0.25697482, 0.10337758, 0.5379051 , 0.2707088 ,
        0.02460349, 0.06105328, 0.42337906, 0.30669105, 0.30637336],
       dtype=float32)>, TensorShape([50]))

In [ ]:
#One hot encoding
l=[0,1,2,3]
tf.one_hot(l,depth=4)



<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
l=[0,1,1,7]
tf.one_hot(l,depth=8)

<tf.Tensor: shape=(4, 8), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#more math operations
ma=tf.range(1,10)
tf.square(ma)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(ma,dtype=float))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(ma,dtype=float))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
#using tf thru np
num=tf.constant(np.array([3,5,7,9]))
num.numpy()
num.dtype


tf.int64

In [ ]:
r3t.dtype #different from numpy tensor

tf.int32